"""Extract native-resolution icons and measure vector chevrons from 30 fps frames.

Inputs are lossless frames decoded from the supplied Home reference videos.
No resizing or sharpening is applied to the source artwork.
"""

import argparse
from pathlib import Path

from PIL import Image


def chevrons(image):
    pixels = image.convert("RGB")
    candidates = []
    for top in range(110, 168):
        core, contrast = [], []
        for x in range(379, 404):
            y = top + 16 - abs(x - 391)
            background = pixels.getpixel((x, 185))[0]
            value = max(pixels.getpixel((x, y + dy))[0] for dy in (-1, 0, 1))
            outside = sum(pixels.getpixel((x, y + dy))[0] for dy in (-5, 5)) / 2
            core.append(max(0, min(1, (value - background) / (255 - background))))
            contrast.append(value - outside)
        candidates.append((sum(contrast) / len(contrast), top, sum(core) / len(core)))
    chosen = []
    for score, top, alpha in sorted(candidates, reverse=True):
        if all(abs(top - previous[0]) > 16 for previous in chosen):
            chosen.append((top, alpha if score > 4 else 0))
        if len(chosen) == 2:
            break
    return sorted(chosen)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("chevron_frames", type=Path)
    parser.add_argument("benefit_frames", type=Path)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    assets = args.root / "assets/images"
    for name, indices in {
        "point": list(range(37, 107)) + [106] * 5,
        "bag": list(range(112, 170)) + list(range(395, 412)),
        "fire": list(range(419, 491)) + [490] * 3,
    }.items():
        frames = [
            Image.open(args.benefit_frames / f"{index:04d}.png")
            .convert("RGB")
            .crop((120, 75, 260, 215))
            for index in indices
        ]
        frames[10].save(assets / f"home_benefit_{name}_still.png")
        frames[0].save(
            assets / f"home_benefit_{name}.png",
            save_all=True,
            append_images=frames[1:],
            duration=[33, 34, 33] * 25,
            loop=0,
            disposal=0,
            blend=0,
        )
        print(f"{name}: 75 frames, 140x140, 2500 ms")
    samples = [
        chevrons(Image.open(args.chevron_frames / f"{index:04d}.png"))
        for index in range(45)
    ]
    output = [
        "// Generated by tool/extract_home_effects.py from Downloads/1.mp4.",
        "// Source-space top Y and white opacity for each chevron, sampled at 30 fps.",
        "const homeChevronFrames = <(double, double, double, double)>[",
    ]
    for (first_y, first_alpha), (second_y, second_alpha) in samples:
        output.append(
            f"  ({first_y:.1f}, {first_alpha:.4f}, {second_y:.1f}, {second_alpha:.4f}),"
        )
    output.append("];")
    (args.root / "lib/ui/home_chevron_motion.dart").write_text("\n".join(output) + "\n")


if __name__ == "__main__":
    main()
